"""creatinf the many to many relationship between labels and notes

Revision ID: 0632e7c523e8
Revises: f24369c9051d
Create Date: 2024-06-13 10:58:36.218806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0632e7c523e8'
down_revision: Union[str, None] = 'f24369c9051d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_association_table',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label_association_table')
    # ### end Alembic commands ###
