"""Changed the Schema for the notes model

Revision ID: 470f6e7f43a6
Revises: 3e16828410f8
Create Date: 2024-06-11 15:33:18.336278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470f6e7f43a6'
down_revision: Union[str, None] = '3e16828410f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
