"""Making some changes in the Notes Models

Revision ID: cb5ef5271c40
Revises: b5ebd12a226b
Create Date: 2024-06-10 16:08:21.070866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb5ef5271c40'
down_revision: Union[str, None] = 'b5ebd12a226b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'reminder',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'reminder',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
